# Generated by Django 4.2.7 on 2023-11-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                ("idade", models.IntegerField(blank=True)),
                ("emial", models.EmailField(max_length=150, verbose_name="email")),
            ],
            options={
                "db_table": "Pessoa",
            },
        ),
    ]
