# Generated by Django 4.2.7 on 2023-12-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0002_rename_emial_pessoa_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pessoa",
            options={
                "ordering": ["nome"],
                "verbose_name": "Pessoa",
                "verbose_name_plural": "Pessoas",
            },
        ),
        migrations.AlterField(
            model_name="pessoa",
            name="email",
            field=models.EmailField(max_length=150, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="pessoa",
            name="idade",
            field=models.IntegerField(blank=True, null=True, verbose_name="Idade"),
        ),
        migrations.AlterField(
            model_name="pessoa",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterModelTable(
            name="pessoa",
            table=None,
        ),
    ]
