# Generated by Django 4.2.7 on 2023-12-28 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0004_categoria"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Categoria",
        ),
    ]
